<a href="https://colab.research.google.com/github/Maitreyautpal/Heart-Disease-prediction/blob/main/heart_desease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [331]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [332]:
df = pd.read_csv('/content/Heart_Disease_Prediction.csv')

In [333]:
df.head()

Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0   70    1                4  130          322             0            2   
1   67    0                3  115          564             0            2   
2   57    1                2  124          261             0            0   
3   64    1                4  128          263             0            0   
4   74    0                2  120          269             0            2   

   Max HR  Exercise angina  ST depression  Slope of ST  \
0     109                0            2.4            2   
1     160                0            1.6            2   
2     141                0            0.3            1   
3     105                1            0.2            2   
4     121                1            0.2            1   

   Number of vessels fluro  Thallium Heart Disease  
0                        3         3      Presence  
1                        0         7       Absence  
2                        0         7      Presence  
3                        1         7       Absence  
4                        1         3       Absence

In [334]:
df.isna().sum().sum()

np.int64(0)

In [335]:
X = df.drop('Heart Disease',axis=1)
y = df['Heart Disease']

In [336]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = pd.DataFrame(scaler.fit_transform(X),columns=X.columns)


In [337]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = pd.DataFrame(le.fit_transform(y),columns=['Heart Disease'])

In [338]:
X

Age  Sex  Chest pain type        BP  Cholesterol  FBS over 120  \
0    0.854167  1.0         1.000000  0.339623     0.447489           0.0   
1    0.791667  0.0         0.666667  0.198113     1.000000           0.0   
2    0.583333  1.0         0.333333  0.283019     0.308219           0.0   
3    0.729167  1.0         1.000000  0.320755     0.312785           0.0   
4    0.937500  0.0         0.333333  0.245283     0.326484           0.0   
..        ...  ...              ...       ...          ...           ...   
265  0.479167  1.0         0.666667  0.735849     0.166667           1.0   
266  0.312500  1.0         0.333333  0.245283     0.312785           0.0   
267  0.562500  0.0         0.333333  0.433962     0.383562           0.0   
268  0.583333  1.0         1.000000  0.433962     0.150685           0.0   
269  0.791667  1.0         1.000000  0.622642     0.365297           0.0   

     EKG results    Max HR  Exercise angina  ST depression  Slope of ST  \
0            1.0  0.290076              0.0       0.387097          0.5   
1            1.0  0.679389              0.0       0.258065          0.5   
2            0.0  0.534351              0.0       0.048387          0.0   
3            0.0  0.259542              1.0       0.032258          0.5   
4            1.0  0.381679              1.0       0.032258          0.0   
..           ...       ...              ...            ...          ...   
265          0.0  0.694656              0.0       0.080645          0.0   
266          0.0  0.778626              0.0       0.000000          0.0   
267          1.0  0.625954              0.0       0.209677          0.5   
268          0.0  0.587786              0.0       0.064516          0.5   
269          1.0  0.282443              1.0       0.241935          0.5   

     Number of vessels fluro  Thallium  
0                   1.000000      0.00  
1                   0.000000      1.00  
2                   0.000000      1.00  
3                   0.333333      1.00  
4                   0.333333      0.00  
..                       ...       ...  
265                 0.000000      1.00  
266                 0.000000      1.00  
267                 0.000000      0.00  
268                 0.000000      0.75  
269                 1.000000      0.00  

[270 rows x 13 columns]

In [339]:
y

Heart Disease
0                1
1                0
2                1
3                0
4                0
..             ...
265              0
266              0
267              0
268              0
269              1

[270 rows x 1 columns]

In [340]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [341]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
model_lc = LogisticRegression()
model_lc.fit(X_train,y_train)

LogisticRegression()

In [342]:
y_pred = model_lc.predict(X_test)
y_pred

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1])

In [343]:
accuracy_score(y_test,y_pred)

0.9259259259259259

In [344]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.97      0.94        33
           1       0.95      0.86      0.90        21

    accuracy                           0.93        54
   macro avg       0.93      0.91      0.92        54
weighted avg       0.93      0.93      0.93        54



In [345]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[32,  1],
       [ 3, 18]])

In [346]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train,y_train)

KNeighborsClassifier()

In [347]:
y_pred = knn_model.predict(X_test)
y_pred

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1])

In [348]:
accuracy_score(y_test,y_pred)

0.8518518518518519

In [349]:
confusion_matrix(y_test,y_pred)

array([[28,  5],
       [ 3, 18]])

In [350]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.85      0.88        33
           1       0.78      0.86      0.82        21

    accuracy                           0.85        54
   macro avg       0.84      0.85      0.85        54
weighted avg       0.86      0.85      0.85        54



In [351]:
from sklearn.svm import SVC
svm_model = SVC()
svm_model.fit(X_train,y_train)

SVC()

In [352]:
y_pred = svm_model.predict(X_test)
y_pred

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1])

In [353]:
accuracy_score(y_test,y_pred)

0.8148148148148148

In [354]:
confusion_matrix(y_test,y_pred)

array([[28,  5],
       [ 5, 16]])

In [355]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85        33
           1       0.76      0.76      0.76        21

    accuracy                           0.81        54
   macro avg       0.81      0.81      0.81        54
weighted avg       0.81      0.81      0.81        54



In [356]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [357]:
y_pred = dt_model.predict(X_test)
y_pred

array([1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1])

In [358]:
accuracy_score(y_test,y_pred)

0.7037037037037037

In [359]:
confusion_matrix(y_test,y_pred)

array([[22, 11],
       [ 5, 16]])

In [360]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.67      0.73        33
           1       0.59      0.76      0.67        21

    accuracy                           0.70        54
   macro avg       0.70      0.71      0.70        54
weighted avg       0.73      0.70      0.71        54



In [361]:
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(X_train,y_train)

GaussianNB()

In [362]:
y_pred = nb_model.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1])

In [363]:
accuracy_score(y_test,y_pred)

0.9074074074074074

In [364]:
confusion_matrix(y_test,y_pred)

array([[32,  1],
       [ 4, 17]])

In [365]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.97      0.93        33
           1       0.94      0.81      0.87        21

    accuracy                           0.91        54
   macro avg       0.92      0.89      0.90        54
weighted avg       0.91      0.91      0.91        54



In [366]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model_lc, X, y, cv=7, scoring='accuracy')
print("Cross Validation Scores:", scores)
print("Mean Accuracy:", scores.mean())


Cross Validation Scores: [0.74358974 0.8974359  0.82051282 0.87179487 0.84210526 0.86842105
 0.84210526]
Mean Accuracy: 0.8408521303258144


In [367]:
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier

# Encode the target variable
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

model = XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    learning_rate=0.20,
    max_depth=4,
    n_estimators=200
)

model.fit(X_train, y_train_encoded)
y_pred = model.predict(X_test)


In [368]:
y_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1])

In [369]:
accuracy_score(y_test_encoded,y_pred)

0.8703703703703703

In [370]:
confusion_matrix(y_test_encoded,y_pred)

array([[31,  2],
       [ 5, 16]])

In [371]:
print(classification_report(y_test_encoded,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.94      0.90        33
           1       0.89      0.76      0.82        21

    accuracy                           0.87        54
   macro avg       0.88      0.85      0.86        54
weighted avg       0.87      0.87      0.87        54



In [372]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Model
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42
)

# Train
rf.fit(X_train, y_train)

# Predict
y_pred = rf.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Accuracy: 0.8333333333333334
[[25  5]
 [ 4 20]]
              precision    recall  f1-score   support

           0       0.86      0.83      0.85        30
           1       0.80      0.83      0.82        24

    accuracy                           0.83        54
   macro avg       0.83      0.83      0.83        54
weighted avg       0.83      0.83      0.83        54



In [373]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf, X, y, cv=7, scoring='accuracy')
print("CV Scores:", scores)
print("Mean Accuracy:", scores.mean())


CV Scores: [0.71794872 0.84615385 0.76923077 0.8974359  0.81578947 0.89473684
 0.84210526]
Mean Accuracy: 0.8262001156737998


In [374]:
from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators':[100,200,300],
    'max_depth':[None,3,5,7,10],
    'min_samples_split':[2,5,10],
    'min_samples_leaf':[1,2,4]
}
grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid=params,
    cv=7,
    scoring='accuracy',
    n_jobs=-1
)
grid.fit(X, y)

GridSearchCV(cv=7, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [None, 3, 5, 7, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='accuracy')

In [375]:
print("Best Accuracy:", grid.best_score_)
print("Best Params:", grid.best_params_)

best_rf = grid.best_estimator_


Best Accuracy: 0.8522267206477733
Best Params: {'max_depth': None, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 300}


In [376]:
confusion_matrix(y_test, y_pred)

array([[25,  5],
       [ 4, 20]])

In [378]:
import joblib as jb
jb.dump(model_lc,'Heart-Disease_model.pkl')
jb.dump(scaler,'scaler.pkl')
jb.dump(X.columns.to_list(),'columns.pkl')

['columns.pkl']